<a href="https://colab.research.google.com/github/komoloantony/pypractice/blob/main/Music.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#** STEPS**

1.   Import The Data
2.   Clean The Data
3.   Split the Data into Trainig/test sets
4.   Creat A Model
5.   Train the Model
6.   Make Predictions
7.   Evaluate and improve

In [1]:
from google.colab import files
files.upload()

Saving music_dataset_.csv to music_dataset_.csv

{'music_dataset_.csv': b'Song,Artist,Genre,Year,Duration_Minutes,Popularity,Typical_Age_Group,Average_Listener_Age\nBlinding Lights,The Weeknd,Pop,2020,3.2,95,16-30,24\nShape of You,Ed Sheeran,Pop,2017,4.1,98,16-35,26\nHUMBLE,Kendrick Lamar,Hip-Hop,2017,2.9,94,18-35,28\nOne Dance,Drake,Hip-Hop,2016,2.5,92,18-35,27\nSomeone Like You,Adele,Soul,2011,4.5,90,25-45,35\nBohemian Rhapsody,Queen,Rock,1975,5.9,97,25-60,40\nSmells Like Teen Spirit,Nirvana,Rock,1991,5.0,93,25-50,38\nBad Guy,Billie Eilish,Pop,2019,3.1,91,16-30,23\nOld Town Road,Lil Nas X,Country,2019,2.4,89,18-40,30\nRolling in the Deep,Adele,Soul,2010,3.8,96,25-45,34\n'}

In [2]:
import pandas as pd
df = pd.read_csv("music_dataset_.csv")
df

,Song,Artist,Genre,Year,Duration_Minutes,Popularity,Typical_Age_Group,Average_Listener_Age
0,Blinding Lights,The Weeknd,Pop,2020,3.2,95,16-30,24
1,Shape of You,Ed Sheeran,Pop,2017,4.1,98,16-35,26
2,HUMBLE,Kendrick Lamar,Hip-Hop,2017,2.9,94,18-35,28
3,One Dance,Drake,Hip-Hop,2016,2.5,92,18-35,27
4,Someone Like You,Adele,Soul,2011,4.5,90,25-45,35
5,Bohemian Rhapsody,Queen,Rock,1975,5.9,97,25-60,40
6,Smells Like Teen Spirit,Nirvana,Rock,1991,5.0,93,25-50,38
7,Bad Guy,Billie Eilish,Pop,2019,3.1,91,16-30,23
8,Old Town Road,Lil Nas X,Country,2019,2.4,89,18-40,30
9,Rolling in the Deep,Adele,Soul,2010,3.8,96,25-45,34

In [4]:
music_data.describe()

             Year  Duration_Minutes  Popularity  Average_Listener_Age
count    10.00000          10.00000    10.00000             10.000000
mean   2009.50000           3.74000    93.50000             30.500000
std      14.83427           1.14037     3.02765              5.930149
min    1975.00000           2.40000    89.00000             23.000000
25%    2010.25000           2.95000    91.25000             26.250000
50%    2016.50000           3.50000    93.50000             29.000000
75%    2018.50000           4.40000    95.75000             34.750000
max    2020.00000           5.90000    98.00000             40.000000

In [4]:
!pip install DecisionTreeClassifier

Collecting DecisionTreeClassifier
  Downloading DecisionTreeClassifier-0.0.7-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from DecisionTreeClassifier) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from DecisionTreeClassifier) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->DecisionTreeClassifier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->DecisionTreeClassifier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->DecisionTreeClassifier) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->DecisionTreeClassifier) (1.17.0)
Downloading DecisionTreeClassifier-0.0.7-py3-none-any.whl (12 kB)
Installing collected packages: DecisionTreeClassifier
Successfully installed DecisionTreeClassifier-0.0.7

In [11]:
from google.colab import files
files.upload()

Saving music_dataset_.csv to music_dataset_.csv

{'music_dataset_.csv': b'Song,Artist,Genre,Year,Duration_Minutes,Popularity,Typical_Age_Group,Average_Listener_Age\nBlinding Lights,The Weeknd,Pop,2020,3.2,95,16-30,24\nShape of You,Ed Sheeran,Pop,2017,4.1,98,16-35,26\nHUMBLE,Kendrick Lamar,Hip-Hop,2017,2.9,94,18-35,28\nOne Dance,Drake,Hip-Hop,2016,2.5,92,18-35,27\nSomeone Like You,Adele,Soul,2011,4.5,90,25-45,35\nBohemian Rhapsody,Queen,Rock,1975,5.9,97,25-60,40\nSmells Like Teen Spirit,Nirvana,Rock,1991,5.0,93,25-50,38\nBad Guy,Billie Eilish,Pop,2019,3.1,91,16-30,23\nOld Town Road,Lil Nas X,Country,2019,2.4,89,18-40,30\nRolling in the Deep,Adele,Soul,2010,3.8,96,25-45,34\n'}

In [13]:
import pandas as pd
music_data = pd.read_csv("music_dataset_.csv")
music_data

,Song,Artist,Genre,Year,Duration_Minutes,Popularity,Typical_Age_Group,Average_Listener_Age
0,Blinding Lights,The Weeknd,Pop,2020,3.2,95,16-30,24
1,Shape of You,Ed Sheeran,Pop,2017,4.1,98,16-35,26
2,HUMBLE,Kendrick Lamar,Hip-Hop,2017,2.9,94,18-35,28
3,One Dance,Drake,Hip-Hop,2016,2.5,92,18-35,27
4,Someone Like You,Adele,Soul,2011,4.5,90,25-45,35
5,Bohemian Rhapsody,Queen,Rock,1975,5.9,97,25-60,40
6,Smells Like Teen Spirit,Nirvana,Rock,1991,5.0,93,25-50,38
7,Bad Guy,Billie Eilish,Pop,2019,3.1,91,16-30,23
8,Old Town Road,Lil Nas X,Country,2019,2.4,89,18-40,30
9,Rolling in the Deep,Adele,Soul,2010,3.8,96,25-45,34

In [33]:
print(music_data.dtypes)
music_data.head()
music_data["Average_Listener_Age"] = pd.to_numeric(music_data["Average_Listener_Age"], errors="coerce")
music_data["Duration_Minutes"] = pd.to_numeric(music_data["Duration_Minutes"], errors="coerce")
music_data["Year"] = pd.to_numeric(music_data["Year"], errors="coerce")
music_data.dropna()

Song                     object
Artist                   object
Genre                    object
Year                      int64
Duration_Minutes        float64
Popularity                int64
Typical_Age_Group        object
Average_Listener_Age      int64
dtype: object

,Song,Artist,Genre,Year,Duration_Minutes,Popularity,Typical_Age_Group,Average_Listener_Age
0,Blinding Lights,The Weeknd,Pop,2020,3.2,95,16-30,24
1,Shape of You,Ed Sheeran,Pop,2017,4.1,98,16-35,26
2,HUMBLE,Kendrick Lamar,Hip-Hop,2017,2.9,94,18-35,28
3,One Dance,Drake,Hip-Hop,2016,2.5,92,18-35,27
4,Someone Like You,Adele,Soul,2011,4.5,90,25-45,35
5,Bohemian Rhapsody,Queen,Rock,1975,5.9,97,25-60,40
6,Smells Like Teen Spirit,Nirvana,Rock,1991,5.0,93,25-50,38
7,Bad Guy,Billie Eilish,Pop,2019,3.1,91,16-30,23
8,Old Town Road,Lil Nas X,Country,2019,2.4,89,18-40,30
9,Rolling in the Deep,Adele,Soul,2010,3.8,96,25-45,34

In [44]:
X = music_data.drop(columns={"Song","Artist","Genre","Popularity","Typical_Age_Group"})#Input cell
X

   Year  Duration_Minutes  Average_Listener_Age
0  2020               3.2                    24
1  2017               4.1                    26
2  2017               2.9                    28
3  2016               2.5                    27
4  2011               4.5                    35
5  1975               5.9                    40
6  1991               5.0                    38
7  2019               3.1                    23
8  2019               2.4                    30
9  2010               3.8                    34

In [23]:
y = music_data[["Song","Artist","Genre","Popularity","Typical_Age_Group"]]#output cell
y

,Song,Artist,Genre,Popularity,Typical_Age_Group
0,Blinding Lights,The Weeknd,Pop,95,16-30
1,Shape of You,Ed Sheeran,Pop,98,16-35
2,HUMBLE,Kendrick Lamar,Hip-Hop,94,18-35
3,One Dance,Drake,Hip-Hop,92,18-35
4,Someone Like You,Adele,Soul,90,25-45
5,Bohemian Rhapsody,Queen,Rock,97,25-60
6,Smells Like Teen Spirit,Nirvana,Rock,93,25-50
7,Bad Guy,Billie Eilish,Pop,91,16-30
8,Old Town Road,Lil Nas X,Country,89,18-40
9,Rolling in the Deep,Adele,Soul,96,25-45

In [50]:
from sklearn.tree import DecisionTreeClassifier

X = music_data[["Year","Duration_Minutes","Average_Listener_Age"]]
y = music_data["Song"]
model = DecisionTreeClassifier()
model.fit(X, y)
predictions = model.predict([[2020,3.8,20],
                             [2017,2.1,19]])

print(predictions)

['Bad Guy' 'Old Town Road']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(